### ISSUE TITLE
Create the scaffold for the kdoc front(or back?)end

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1964]
We need to expose `kdoc` from the command line. I've created a separate mvn module `kdoc` but I'm not sure how to hook it further. I don't want to use other backends as a model because this command doesn't have separate kompile/krun phases.

The `kdoc` module is here: https://github.com/kframework/k/pull/1961
(the implementation is not complete, but it has all the basic ingredients, including latex generation for both outer and inner)

This guide is likely outdated so I haven't tried following it:
https://github.com/kframework/k/wiki/Creating-a-Code-Module

@dwightguth, I would appreciate your help with this. It is likely a half-an-hour job for you while it would take me much longer. I just need the basic scaffold classes, you don't need to hook it to the `KDoc` class.
Also, feel free to add it to that branch if you like.

**Comment by cos** [comment]
@edgar-pek, I'm not using the implementation in the `kdoc` branch because it looks like it is based on the compiled module. Let me know if I'm wrong.

**Comment by cos** [comment]
Basically, I'm trying to keep this as small as possible, if possible.

**Comment by edgar-pek** [comment]
You are right, @cos. Your approach looks much cleaner than what I had, btw.

**Comment by dwightguth** [comment]
You are not going to be able to generate pdfs of all the  definitions in the tutorial in a reasonable time frame if you try to reparse each one of them.

**Comment by cos** [comment]
Considering the approach, I need to parse each one of them with the slower `e-kore.k`-based parser anyhow.
At most I could save time on the KIL-to-KORE pipeline parsing, but that should be fairly fast generally, especially as I'm not parsing the rules at all. In that respect, avoiding the standard compilation pipeline is useful.

**Comment by dwightguth** [comment]
sorry I'm confused. You're not parsing the rules at all? how then can you interpret the production's latex attributes?

**Comment by cos** [comment]
I'm only parsing the "outer" parts of definitions. Rules in most definitions remain as bubbles. The only rules that are parsed are for the definition File/String (let's call it target) you're generating latex from, and they're only parsed once.
Because we still rely on KIL-to-KORE to get a `org.kframework.defintion.Definition`, the target is processed twice. Once by KIL-to-KORE to get a `Definition` and once by our parser using `e-kore.k` to get the meta-level (the full-K, not KORE, meta-level). The meta-level contains bubbles which are then parsed using the `Definition` from KIL-to-KORE.

**Comment by dwightguth** [comment]
Okay but that means you have to point kdoc both to a source (to get the outer) and to a compiled definition (to get the inner) at the same time, right? Or am I misunderstanding?

**Comment by cos** [comment]
The compiled definition is not needed. I just need as input the source (and lookup directories). From there I get a non-compiled definition from KIL-to-KORE which I then use along with `e-kore.k` to generate the latex.

**Comment by cos** [comment]
So I need the scaffold for something that exposes roughly the same inputs as `Kompile`.

**Comment by dwightguth** [comment]
Okay. I would suggest taking a look at kdep then. It's a tool I wrote
recently to provide makefile integration with k definitions. The code is
pretty much entirely self contained to the org.kframework.kdep package, and
it does very little besides accept all the inputs needed to perform outer
parsing. You should be able to make use of most of it with only minimal
modifcations. And the boot sequence wiring for kdoc is already in place in
org.kframework.kdoc. You just will need to strip out the code of the
frontend, module, and options and replace it with something more similar to
kdep. I can help if you run into issues. But it would be good for someone
at the university to understand this part of the code base.

**Comment by dwightguth** [comment]
After talking with Grigore I have agreed to work on this this afternoon. There should be a pull request for it out shortly.

**Comment by dwightguth** [comment]
fixed in #1971. I suggest you steal the code and adapt it into the form you want it. Everything is more or less there with one exception. The kdoc backends are not wired in this because they have not been updated and still rely on Context which we don't have anymore. So what I suggest you do is to modify the PosterBackend interface to your satisfaction, create a LatexBackend class that implements the new PosterBackend, and then add the following line to KDocModule.java after line 35:

```
posterBinder.addBinding("latex").to(LatexBackend.class);
```

You should be able to add other formats the same way, and they will have access to anything you want to inject into them in their creation, although I would suggest making them as simple as possible and passing as much as possible in from KDocFrontEnd which has been wired to have access to the currently selected poster backend.

**Comment by cos** [comment]
to be honest, I still don't understand how things are wired. I tried to follow your instructions. Is this it?
https://github.com/dwightguth/k/compare/kdoc...kframework:hotfix/kdoc-preparation?expand=1

**Comment by cos** [comment]
(left some comments in as I might want to reimplement part of that code)

**Comment by dwightguth** [comment]
That should work although I think you probably want to keep parsing as part of the frontend otherwise you're going to have to do the work of parsing in each backend, which would duplicate code.

**Comment by cos** [comment]
So, which is the frontend and which is the backend here? As far as I understand the tex/pdf generation, it is effectively only one step at command line.

**Comment by dwightguth** [comment]
So the old functionality was one step because it took an already parsed
definition and converted it to latex. But you are parsing again. So you
need two steps. The frontend would be KDocFrontEnd and it would call the
parser to parse the definition and then pass it to the backend which
implements PosterBackend which would take a parsed definition and convert
it to whatever poster format the user specified.
