### ISSUE TITLE
ktest --- rejecting multiple tests sharing a definition without different directories

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#205]
The new ktest missed a feature that rejects a cofiguration file when multiple test elements that share the same definition with different kompile options are given with the same directory attribute.

@osa1 already knew this, but this is just a gentle reminder.

**Comment by grosu** [comment]
Actually thanks for telling us, because I was about to complain about an exception that ktest is throwing on the exercises' folder:

```
Running /home/grosu/k-private/tutorial/2_languages/2_kool/2_typed/1_dynamic/exercises/private-members/kool-typed-dynamic.k programs... (52 in total, 3 with input, 51 with output, 0 with error)
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.ktest.Test.TestCase.searchPrograms(TestCase.java:230)
    at org.kframework.ktest.Test.TestCase.getPrograms(TestCase.java:116)
    at org.kframework.ktest.Test.TestSuite.runKRunSteps(TestSuite.java:276)
    at org.kframework.ktest.Test.TestSuite.run(TestSuite.java:113)
    at org.kframework.ktest.KTest.run(KTest.java:49)
    at org.kframework.ktest.KTest.main(KTest.java:92)
    at org.kframework.main.Main.main(Main.java:53)
^C
```

Exercises make use of the same definition but with different compilation options, so ... I will wait until you guys fix this and then will try the examples again.

**Comment by andreiarusoaie** [comment]
I get the same exception as Grigore for a simple test without having any other test which uses the same definition. I think we should report some useful error message instead of an exception.

**Comment by osa1** [comment]
Yes, this is an unimplemented feature and I'm working on it. (I think we also have another bug report just for this)

**Comment by osa1** [comment]
@andreiarusoaie can you please share with me this problematic tests? I can't reproduce this error.

**Comment by osa1** [comment]
@andreiarusoaie I fixed this problem, please pull latest version and try again.

**Comment by andreiarusoaie** [comment]
Sorry @osa1. I was not around. I still get the same error from ktest, but I'll try to find what goes wrong myself because it happens only on fmse Jenkins. Thanks anyway!

**Comment by osa1** [comment]
It's impossible to get same error because that code is changed. Please
update fmse build.

---

Ömer Sinan Aðacan
http://osa1.net

2013/12/7 Andrei Arusoaie notifications@github.com

**Comment by andreiarusoaie** [comment]
@osa1 that line of code which throws the exception is still there: https://github.com/kframework/k/blob/master/src/javasources/KTool/src/org/kframework/ktest/Test/TestCase.java#L241

The only difference is that the ktest continues even if the exception is thrown. Please look at https://fmse.info.uaic.ro/jenkins/job/symbolic-online-tests/226/console
and look at the Git Revision number (shown when running ant) which is:

```
...
makeversion:
     [echo] ./lib/version.txt
     [echo] K-framework nightly build.
     [echo] Git Revision: 7a3f107
     [echo] Build date: Sun Dec 8 08:15:10 EET 2013

BUILD SUCCESSFUL
```

Moreover, the build updates itself from the GitHub repository. Let me investigate this and I will give you some feedback on this.

**Comment by andreiarusoaie** [comment]
Omer I think I found it! The problem was a broken symbolic link into a hidden dir. Java acts weird when it deals with symbolic links; from my knowledge, I think we should use "getCanonicalPath" for files before instantiating File objects on paths.

I fixed my tests by simply removing the whole hidden directory (I don't even know how it got in those examples). However, do we need to also look into hidden directories? I believe it would be an optimization not to look in there, because we don't usually put tests there. From the user perspective it would be nice to catch that exception somewhere and give a  better error message.

**Comment by osa1** [comment]
> However, do we need to also look into hidden directories? I believe it would be an optimization not to look in there, because we don't usually put tests there. From the user perspective it would be nice to catch that exception somewhere and give a better error message.

I don't know. Currently ktest searches through all kinds of folders. In what case do you want to see an error message?

Also, I still can't fix anything because like I said I can't reproduce your problem.

**Comment by osa1** [comment]
Can we close this issue now?

**Comment by dwightguth** [comment]
Ping?
